### ISSUE TITLE
Include filter step in SF to TW scenario

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis-qe#109]
@rhuss commented on [Fri Oct 06 2017](https://github.com/syndesisio/syndesis-integration-runtime/issues/18)

@dsimansk commented on [Tue Oct 03 2017](https://github.com/syndesisio/syndesis-rest-tests/issues/3)

Based on feedback from Keith pls include filter step that will be based on string with hashtag, e.g. `#salute` to cover common usage of hashtags on Twitter.

Example syndesis.yml:
```
---
flows:
- steps:
  - kind: endpoint
    uri: twitter-mention-connector--KvSUw7eYMcWe1kmZueI:MENTIONS
  - kind: filter
    expression: ${body.text} contains '#salute'
    steps:
    - kind: endpoint
      uri: atlas:mapping-step-3.json
    - kind: endpoint
      uri: salesforce-upsert-sobject--KvSV1v9YMcWe1kmZueJ?sObjectIdName=TwitterScreenName__c&sObjectName=Contact
```

---

@dsimansk commented on [Wed Oct 11 2017](https://github.com/syndesisio/syndesis-integration-runtime/issues/18#issuecomment-335772029)

@rhuss pls can you elaborate why this issue was moved here? If @zregvart is going to include it it some integration test, that's probably something @tplevko could take over.

---

@rhuss commented on [Thu Oct 12 2017](https://github.com/syndesisio/syndesis-integration-runtime/issues/18#issuecomment-336031554)

@dsimansk sorry, I thought this was the issue to _fix_ hashtags in the filter. Overlooked that its about writing a _test_ for it. Feel free to move it back again.
